title: "Beyond the Basics: Statistics & Applications"
description: "A blog about statistical concepts and applications"
author: "Kalani Hasanthika"
url: "https://khasanthika.github.io"
remote_theme: "mtsmfm/tale"
